"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

interface RoomSummary { slug: string; name: string; createdAt: string; participants: number; messages: number; versions: number; }
const steps = ["Name", "Brief", "Parameters"];

export default function HomePage() {
  const router = useRouter();
  const [step, setStep] = useState(0), [name, setName] = useState(""), [brief, setBrief] = useState(""), [constraints, setConstraints] = useState("");
  const [creating, setCreating] = useState(false), [error, setError] = useState<string | null>(null), [joinSlug, setJoinSlug] = useState(""), [showRooms, setShowRooms] = useState(false);
  const [rooms, setRooms] = useState<RoomSummary[]>([]), [confirmSlug, setConfirmSlug] = useState<string | null>(null), [closingSlug, setClosingSlug] = useState<string | null>(null);
  const loadRooms = useCallback(async () => { try { const res = await fetch("/api/rooms"); if (res.ok) setRooms((await res.json()).rooms); } catch { /* History is non-critical. */ } }, []);
  useEffect(() => { void loadRooms(); }, [loadRooms]);
  const closeRoom = useCallback(async (slug: string) => { setClosingSlug(slug); setError(null); try { const res = await fetch(`/api/rooms/${slug}`, { method: "DELETE" }); if (!res.ok) { const data = await res.json().catch(() => ({})); throw new Error(data.error ?? "Could not close the room"); } setRooms((list) => list.filter((room) => room.slug !== slug)); } catch (err) { setError(err instanceof Error ? err.message : "Could not close the room"); } finally { setClosingSlug(null); setConfirmSlug(null); } }, []);
  const create = async () => { if (!name.trim() || !brief.trim() || creating) return; setCreating(true); setError(null); try { const res = await fetch("/api/rooms", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), brief: brief.trim(), constraints: constraints.trim() || undefined }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error ?? "Could not create the room"); router.push(`/room/${data.roomSlug}`); } catch (err) { setError(err instanceof Error ? err.message : "Could not create the room"); setCreating(false); } };
  const next = () => { if (step === 0 && name.trim()) setStep(1); else if (step === 1 && brief.trim()) setStep(2); };
  return <main className="onboarding-shell">
    <header className="onboarding-header"><button type="button" onClick={() => setStep(0)} className="brand-mark" aria-label="Start a new design space"><span className="brand-symbol"><i /><i /><i /></span><span>Itera</span></button><div className="header-status"><span className="status-dot" /> Private workspace</div></header>
    <section className="onboarding-grid">
      <div className="onboarding-intro"><p className="eyebrow">Collaborative 3D design</p><h1>Make the first<br /><em>version clear.</em></h1><p className="intro-copy">Set the direction once. Your team can then review, iterate, and keep every decision attached to the product.</p><div className="product-orbit" aria-hidden="true"><div className="orbit-rings" /><div className="product-form"><span /><span /><span /></div><div className="orbit-label label-top">OBJECT / 001</div><div className="orbit-label label-bottom">READY FOR REVIEW</div></div><p className="intro-note"><span>01</span> A deliberate starting point beats a blank canvas.</p></div>
      <div className="onboarding-panel"><div className="stepper" aria-label={`Step ${step + 1} of 3`}>{steps.map((label, index) => <button key={label} type="button" onClick={() => index < step && setStep(index)} className={`step ${index === step ? "is-active" : ""} ${index < step ? "is-complete" : ""}`}><span>{index < step ? "✓" : `0${index + 1}`}</span>{label}</button>)}</div>
        <div className="form-stage">{step === 0 && <><p className="stage-kicker">Start a project</p><h2>What are you making?</h2><p className="stage-description">Give your shared design space a name everyone will recognize.</p><label className="field-label" htmlFor="product-name">Project name</label><input id="product-name" autoFocus value={name} onChange={(e) => setName(e.target.value)} onKeyDown={(e) => e.key === "Enter" && next()} placeholder="Insulated travel mug" className="onboarding-input" /><p className="field-hint">You can rename this any time.</p></>}{step === 1 && <><p className="stage-kicker">Define the intent</p><h2>Give it a useful brief.</h2><p className="stage-description">Describe the object, its materials, and the details that matter most.</p><label className="field-label" htmlFor="design-brief">Design brief</label><textarea id="design-brief" autoFocus value={brief} onChange={(e) => setBrief(e.target.value)} rows={6} placeholder="A 400ml double-walled stainless steel travel mug with a tapered body, silicone grip, and a screw-on lid." className="onboarding-input onboarding-textarea" /><p className="field-hint">Specific direction makes better iterations.</p></>}{step === 2 && <><p className="stage-kicker">Add guardrails</p><h2>Any non-negotiables?</h2><p className="stage-description">Constraints help your team make decisions that survive the journey to production.</p><label className="field-label" htmlFor="constraints">Manufacturing constraints <span>Optional</span></label><textarea id="constraints" autoFocus value={constraints} onChange={(e) => setConstraints(e.target.value)} rows={5} placeholder="Injection-moulded, 2mm minimum wall thickness, no undercuts." className="onboarding-input onboarding-textarea" /><div className="ready-note"><span>✦</span><div><strong>Your room is ready</strong><br />You&apos;ll be able to invite collaborators next.</div></div></>}{error && <p className="form-error">{error}</p>}</div>
        <div className="form-actions">{step > 0 ? <button type="button" onClick={() => setStep(step - 1)} className="back-button">Back</button> : <span />}{step < 2 ? <button type="button" disabled={step === 0 ? !name.trim() : !brief.trim()} onClick={next} className="primary-button">Continue <span>→</span></button> : <button type="button" disabled={!name.trim() || !brief.trim() || creating} onClick={() => void create()} className="primary-button">{creating ? "Creating room…" : "Create design space"} {!creating && <span>→</span>}</button>}</div>
      </div>
    </section>
    <section className="returning-section"><button type="button" className="returning-toggle" onClick={() => setShowRooms(!showRooms)}><span>Returning to a workspace?</span><span>{showRooms ? "−" : "+"}</span></button>{showRooms && <div className="returning-content"><div className="join-row"><input value={joinSlug} onChange={(e) => setJoinSlug(e.target.value)} onKeyDown={(e) => e.key === "Enter" && joinSlug.trim() && router.push(`/room/${joinSlug.trim()}`)} placeholder="Enter room code" className="onboarding-input" /><button type="button" disabled={!joinSlug.trim()} onClick={() => joinSlug.trim() && router.push(`/room/${joinSlug.trim()}`)} className="join-button">Join room</button></div>{rooms.length > 0 && <div className="room-list">{rooms.map((room) => <div key={room.slug} className="room-row"><button type="button" onClick={() => router.push(`/room/${room.slug}`)}><strong>{room.name}</strong><small>{room.slug} · {room.versions} {room.versions === 1 ? "version" : "versions"} · {room.participants} {room.participants === 1 ? "person" : "people"}</small></button>{confirmSlug === room.slug ? <div className="delete-confirm"><span>Delete?</span><button type="button" onClick={() => void closeRoom(room.slug)} disabled={closingSlug === room.slug}>Yes</button><button type="button" onClick={() => setConfirmSlug(null)}>No</button></div> : <button type="button" onClick={() => setConfirmSlug(room.slug)} className="close-room">Close</button>}</div>)}</div>}</div>}</section>
  </main>;
}
